from days import *
if __name__ == "__main__":
    print(f'day 1: {day1.solve("real/1.csv",1),day1.solve("real/1.csv",3)}')
    print(f'day 2: {day2.solve("real/2.csv","a"),day2.solve("real/2.csv","b")}')
    print(f'day 3: {day3.solve("real/3.csv","a"),day3.solve("real/3.csv","b")}')
    print(f'day 4: {day4.solve("real/4.csv","a"),day4.solve("real/4.csv","b")}')
    print(f'day 5: {day5.solve("real/5.csv",-1),day5.solve("real/5.csv",1)}')
    print(f'day 6: {day6.solve("real/6.csv",4),day6.solve("real/6.csv",14)}')
    print(f'day 7: {day7.solve("real/7.csv")}')
    print(f'day 8: {day8.solve("real/8.csv")}')
    print(f'day 9: {day9.solve("real/9.csv",2),day9.solve("real/9.csv",10)}')
    print(f'day 10: {day10.solve("real/10.csv")}')
    print(f'day 11: {day11.solve("real/11.csv",20)},{day11.solve("real/11.csv",10000)}')
    print(f'day 12: {day12.solve("real/12.csv")}')
    print(f'day 13: {day13.solve("real/13.csv")}')
    print(f'day 14: {day14.solve("real/14.csv",True),day14.solve("real/14.csv")}')
    print(f'day 15: {day15.solve("real/15.csv")}')
